---
- hosts: localhost
  tasks:
    - name: "Install homebrew packages"
      # become: true
      # become_user: root
      community.general.homebrew:
        name: [
          # macos specific
          "zsh-autosuggestions",
          "zsh-syntax-highlighting",
          "zsh-autocomplete",

          # editor
          "neovim",

          # utils
          "git",
          "lftp",
          "netcat",
          "zoxide",
          "eza",
          "yazi",
          "tree",
          "bat",
          "fzf",
          "fd",
          "ripgrep",
          "htop",
          "delta",
          "lazygit",
          "lazydocker",
          "luarocks",
          "jq",
          "yq",
          "nb",
          "make",
          "just",
          "tmux",
          "tmuxinator",
          "subversion",
          "sshpass",
          "p7zip",

          # build systems
          "maven",
          "gradle",
          "ant",
          "uv",

          # languages
          "python3",
          "go",
          "openjdk@17",
          "zig",
          "lua",

          #database
          "redis",

          # dotfiles
          "stow",

          # ai
          "ollama"
        ]
        state: present
        update_homebrew: yes
